name: On Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13 # Updated to support Apple Silicon (M1/M2 Macs)
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin # Using Temurin distribution for OpenJDK
          java-version: 17 # Updated to JDK 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn clean -q compile